### ISSUE TITLE
Tables don't seem to match dataset spreadsheet

### ISSUE THREAD

**Issue by aj-gh** [recdnsfp/recdnsfp.github.io#1]
Tables on slide #19 and #20 don't seem to match what is provided in the measurement spreadsheets, at least when filtering on the "hijacked" column. Slide #19 (Google) lists 120 hijacks in total while the spreadsheet seems to contain 115. For slide #20 (OpenDNS) it's 94 vs 81.
Both slides seem to contain twice the amount of affected probes for AS6830 when comparing with the spreadsheets.
Were these tables created based on a different dataset, am I doing something wrong or is there a bug?

**Comment by pforemski** [comment]
Hi, the spreadsheets give you raw data, before classification. Note that the "hijacked" column has a label "hijacked (gt)" - where "gt" means "ground-truth". What you see in the last column is our current attempt at collecting ground-truth using the method I explained during my talk (just 7 features).

Thus, the slides #19 and #20 you're referring too have a different source of data than what you see in the spreadsheets. For these slides, we took the output of classification using our Random Forest models, both of which you can find at https://github.com/recdnsfp/classify/tree/master/results

Please let me know if this explains what you see in the presentation. Thanks for asking!

**Comment by aj-gh** [comment]
Thanks.
